// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "0a54d4f27193ab2ed1a69ed96ae01d2349fd0128afdb68dff322d9cf25528091")
