// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "c5652882fefaf282bb9d5839ae169b9c61295563d1a9f542db60366a4722bc88")
