// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "8a00f5fbb07188997cfe039c367818fe2add97c584833c1a5900cd8d19251936")
